name: koszek.com
url: https://www.koszek.com
author:
  name: "Wojciech Adam Koszek"
  email: wojciech@koszek.com
title: "Wojciech Adam Koszek - personal website"
copyright: "Wojciech Adam Koszek, 2012-2017"
encoding: utf-8
timezone: America/San_Francisco

theme: wojciech

plugin:
  google_analytics:
    id: UA-8027537-3
  statcounter:
    sc_security: "b542d462"
    sc_project: "10468040"

social:
  twitter: https://www.twitter.com/wkoszek
  linkedin: https://www.linkedin.com/in/wkoszek
  github: https://github.com/wkoszek
  pinterest: dd
  pinboard: dd

verify:
  pinterest: 35dedfd4f697e6e974b0ae6631ca7351

monitor:
  render:
    one: 'md$'
    all: '(\.js$|\.css$|\.erb$)'

dirs:
  source: source
  dest: build
  #pattern: '**/*.md'
  pattern: '**/2012-05-13-unfriendly_it.html.md'
  #pattern: 'index.md'
